//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationWorker.Domain.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DonationWorker.Domain.Shared.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Comando não deve ser nulo.
        /// </summary>
        public static string _400_COMMAND_INVALID {
            get {
                return ResourceManager.GetString("400_COMMAND_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF é obrigatório..
        /// </summary>
        public static string _400_CPF_REQUIRED {
            get {
                return ResourceManager.GetString("400_CPF_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo E-mail é obrigatório..
        /// </summary>
        public static string _400_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("400_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Guid é obrigatório.
        /// </summary>
        public static string _400_GUID_REQUIRED {
            get {
                return ResourceManager.GetString("400_GUID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome Completo deve possuir entre 5 e 100 caracteres.
        /// </summary>
        public static string _400_NAME_LENGTH_INVALID {
            get {
                return ResourceManager.GetString("400_NAME_LENGTH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome Completo é obrigatório..
        /// </summary>
        public static string _400_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("400_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password é obrigatório.
        /// </summary>
        public static string _400_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("400_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil invalido.
        /// </summary>
        public static string _400_PROFILE_INVALID {
            get {
                return ResourceManager.GetString("400_PROFILE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo solicitante não deve ser nulo.
        /// </summary>
        public static string _400_REQUESTER_REQUIRED {
            get {
                return ResourceManager.GetString("400_REQUESTER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status invalido.
        /// </summary>
        public static string _400_STATUS_INVALID {
            get {
                return ResourceManager.GetString("400_STATUS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status é obrigatório.
        /// </summary>
        public static string _400_STATUS_REQUIRED {
            get {
                return ResourceManager.GetString("400_STATUS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Token JWT é requerido.
        /// </summary>
        public static string _400_TOKEN_REQUIRED {
            get {
                return ResourceManager.GetString("400_TOKEN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe usuario cadastrado com o e-mail informado..
        /// </summary>
        public static string _400_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("400_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Valor nao pode ser nulo.
        /// </summary>
        public static string _400_VALUE_REQUIRED {
            get {
                return ResourceManager.GetString("400_VALUE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida.
        /// </summary>
        public static string _401_INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("401_INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token revogado (Usuário efetuou logout ou foi bloqueado)..
        /// </summary>
        public static string _401_TOKEN_REVOKED {
            get {
                return ResourceManager.GetString("401_TOKEN_REVOKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um gestor não pode suspender o próprio perfil..
        /// </summary>
        public static string _403_FORBIDDEN_CANNOT_SUSPEND_SELF {
            get {
                return ResourceManager.GetString("403_FORBIDDEN_CANNOT_SUSPEND_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorreto.
        /// </summary>
        public static string _403_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("403_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas o próprio usuário ou gestores da ONG podem alterar outros usuários..
        /// </summary>
        public static string _403_USER_CANNOT_ALTER {
            get {
                return ResourceManager.GetString("403_USER_CANNOT_ALTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas administradores podem alterar o nível de acesso e status de usuários..
        /// </summary>
        public static string _403_USER_CANNOT_MODIFY_ACCESS_LEVEL {
            get {
                return ResourceManager.GetString("403_USER_CANNOT_MODIFY_ACCESS_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não pode alterar seu próprio nível de acesso e status por segurança..
        /// </summary>
        public static string _403_USER_CANNOT_MODIFY_OWN_ACCESS_LEVEL {
            get {
                return ResourceManager.GetString("403_USER_CANNOT_MODIFY_OWN_ACCESS_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas o próprio usuário pode se deletar ou gestores da ONG podem remover outros usuários..
        /// </summary>
        public static string _403_USER_CANNOT_REMOVE {
            get {
                return ResourceManager.GetString("403_USER_CANNOT_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario marcado para exclusão de dados (LGPD). Caso deseje informações adicionais entrar em contato com suporte@conexao-solidaria.com.br.
        /// </summary>
        public static string _403_USER_DELETED {
            get {
                return ResourceManager.GetString("403_USER_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não permitido.
        /// </summary>
        public static string _403_USER_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("403_USER_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario suspenso. Favor entrar em contato com o e-mail  suporte@conexao-solidaria.com.br.
        /// </summary>
        public static string _403_USER_SUSPENDED {
            get {
                return ResourceManager.GetString("403_USER_SUSPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campanha nao esta ativa e nao pode receber doacoes..
        /// </summary>
        public static string _422_CAMPAIGN_CANNOT_ADD_DONATION {
            get {
                return ResourceManager.GetString("422_CAMPAIGN_CANNOT_ADD_DONATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF já existente na lista de usuários.
        /// </summary>
        public static string _422_CPF_DUPLICATED {
            get {
                return ResourceManager.GetString("422_CPF_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF e invalido..
        /// </summary>
        public static string _422_CPF_INVALID {
            get {
                return ResourceManager.GetString("422_CPF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF deve ter 11 caracteres.
        /// </summary>
        public static string _422_CPF_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("422_CPF_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de E-mail Invalido.
        /// </summary>
        public static string _422_EMAIL_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("422_EMAIL_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo e-mail deve ter no máximo 100 caracteres.
        /// </summary>
        public static string _422_EMAIL_LENGTH_INVALID {
            get {
                return ResourceManager.GetString("422_EMAIL_LENGTH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password deve conter: letra maiúscula, minúscula, número e caracter especial..
        /// </summary>
        public static string _422_PASSWORD_COMPLEXITY {
            get {
                return ResourceManager.GetString("422_PASSWORD_COMPLEXITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password deve ter ao menos um numero.
        /// </summary>
        public static string _422_PASSWORD_REQUIRES_DIGIT {
            get {
                return ResourceManager.GetString("422_PASSWORD_REQUIRES_DIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password deve ter ao menos uma letra minuscula.
        /// </summary>
        public static string _422_PASSWORD_REQUIRES_LOWERCASE {
            get {
                return ResourceManager.GetString("422_PASSWORD_REQUIRES_LOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password deve ter ao menos um caracter especial.
        /// </summary>
        public static string _422_PASSWORD_REQUIRES_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("422_PASSWORD_REQUIRES_SPECIAL_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password deve ter ao menos uma letra maiuscula.
        /// </summary>
        public static string _422_PASSWORD_REQUIRES_UPPERCASE {
            get {
                return ResourceManager.GetString("422_PASSWORD_REQUIRES_UPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password deve ter no mínimo 8 caracteres.
        /// </summary>
        public static string _422_PASSWORD_TOO_SHORT {
            get {
                return ResourceManager.GetString("422_PASSWORD_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já cadastrado.
        /// </summary>
        public static string _422_USER_DUPLICATED {
            get {
                return ResourceManager.GetString("422_USER_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível alterar um usuário deletado..
        /// </summary>
        public static string _422_USER_REMOVED {
            get {
                return ResourceManager.GetString("422_USER_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível alterar um usuário suspenso..
        /// </summary>
        public static string _422_USER_SUSPENDED {
            get {
                return ResourceManager.GetString("422_USER_SUSPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor deve ser maior que 0.
        /// </summary>
        public static string _422_VALUE_GREATER_0 {
            get {
                return ResourceManager.GetString("422_VALUE_GREATER_0", resourceCulture);
            }
        }
    }
}
