<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-DonationWorker-71c671df-6e6b-4986-8072-67b84db04613</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
	<PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.19" />
	<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.4.3" />
	<PackageReference Include="MassTransit" Version="8.0.0" />
	<PackageReference Include="MassTransit.RabbitMQ" Version="8.0.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.0" />
	<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
	<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.1" />
	<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
	<PackageReference Include="prometheus-net" Version="8.2.1" />
	<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Domain\Shared\Resources\Errors.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Errors.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Domain\Shared\Resources\Errors.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Errors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
